//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StonePayments.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StonePaymentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StonePaymentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StonePayments.Business.StonePaymentResource", typeof(StonePaymentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Amount deve ser no mínimo igual a 0.1 !.
        /// </summary>
        public static string AmountAtLeastTenCents {
            get {
                return ResourceManager.GetString("AmountAtLeastTenCents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Card não foi encontrado !.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CardNumber deve conter entre 12 a 19 dígitos !.
        /// </summary>
        public static string CardNumberBetween12_19_Digits {
            get {
                return ResourceManager.GetString("CardNumberBetween12_19_Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CardNumber não pode ser nulo !.
        /// </summary>
        public static string CardNumberNotNull {
            get {
                return ResourceManager.GetString("CardNumberNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente não possui saldo disponível !.
        /// </summary>
        public static string CustomerHasNoAvailableBalance {
            get {
                return ResourceManager.GetString("CustomerHasNoAvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente não foi encontrado !.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Number deve ser no mínimo igual a 1 !.
        /// </summary>
        public static string NumberMinValueEqualOne {
            get {
                return ResourceManager.GetString("NumberMinValueEqualOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Password deve conter entre 4 a 6 dítigos !.
        /// </summary>
        public static string PasswordBetween4_6_Digits {
            get {
                return ResourceManager.GetString("PasswordBetween4_6_Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do cartão é inválida !.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha não pode ser nulo !.
        /// </summary>
        public static string PasswordIsNotBeNull {
            get {
                return ResourceManager.GetString("PasswordIsNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando dados da transação para o servidor, aguarde ....
        /// </summary>
        public static string SendingTransactionToServer {
            get {
                return ResourceManager.GetString("SendingTransactionToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao enviar transação do cliente para o servidor !.
        /// </summary>
        public static string SendTransactionError {
            get {
                return ResourceManager.GetString("SendTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação enviada com sucesso !.
        /// </summary>
        public static string TransactionSendOk {
            get {
                return ResourceManager.GetString("TransactionSendOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validação.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
    }
}
